FUNCTION getProPath RETURNS CHARACTER ():
    RETURN PROPATH.
END FUNCTION.

FUNCTION getWorkingDirectory RETURN CHARACTER ():
    FILE-INFO:FILE-NAME = ".".
    RETURN FILE-INFO:FULL-PATHNAME.
END FUNCTION.
        
